### ISSUE TITLE
[FATA][Freecli][Subscriber Module] [Configuration] open config/subscriber.yaml: no such file or directory

### ISSUE THREAD

**Issue by williamlin0504** [Srajdax/free5gc-cli#2]
Hi there, 
I'm trying to use the subscriber mode, but it seems the path isn't correct as the picture below:
![image](https://user-images.githubusercontent.com/25023734/101610128-cb6b6e00-3a42-11eb-8154-bd90238af82b.png)
and there sure is a file named `subscriber.yaml` in /config
![image](https://user-images.githubusercontent.com/25023734/101610337-14bbbd80-3a43-11eb-934b-70d354868617.png)
so I'm guessing I'm using the wrong file to run 
`sudo ./freecli` 
and else if I'm trying to run the `sudo ./freecli` in `/free5gc-cli` it would say 
![image](https://user-images.githubusercontent.com/25023734/101610432-32892280-3a43-11eb-8f22-7429d971d28e.png)

Thank you for reading my problems.

William Lin,
Taiwan, Fu Jen Catholic University, Information Management Master Student

**Comment by shynuu** [comment]
Hi @williamlin0504,

Please follow these steps to download and compile the utility

```bash
git clone https://github.com/srajdax/free5gc-cli.git
cd free5gc-cli
go mod download
go build -o freecli5G -x freecli.go
```

And to run it

```bash
sudo ./freecli5G
```

The freecli directory inside the freecli-5gc is quiet confusing I admin it. When compiling freecli5G you must not `cd` into the `freecli` directory but stay at the root of the `freecli-5gc`

I have updated the wiki to avoid the confusion in the future.

Please, let me know if it solves your issue.

Youssouf

**Comment by williamlin0504** [comment]
Hi @Srajdax ,
Thank you for replying so fast, it did solve my problem
I just re-run the
`go build -o freecli5G -x freecli.go`
and the `freecli5G` appeared then the subscriber mode is fine to use, as the picture below:

![image](https://user-images.githubusercontent.com/25023734/101611726-d0c9b800-3a44-11eb-8938-57d4a8bc0d8e.png)

Thanks a lot.

William Lin

**Comment by shynuu** [comment]
You're welcome.

I'm closing the issue.
