### ISSUE TITLE
Error in loading gNB module

### ISSUE THREAD

**Issue by pragnyakiri** [Srajdax/free5gc-cli#3]
Hi,

I am getting the error as in attached screenshot while loading the gNB module.
Could you please help me resolve this error ?
![Screenshot 2020-12-15 at 2 17 34 PM](https://user-images.githubusercontent.com/75774210/102192483-d873db80-3ee0-11eb-85fb-e3d129c954b8.png)

Thank you.

**Comment by shynuu** [comment]
Hi @pragnyakiri,

Seems to be an SCTP connection issue with the AMF.

Can you please indicate me the following informations:

- OS Version
- Golang Version

Also, can you check that AMF is running and is reachable on its SCTP port ?

**Comment by pragnyakiri** [comment]
Thanks for your reply.
I installed free5gc afresh and it worked.
